//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba25_Pharmacy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Pharmacy.mdf;" +
            "Integrated Security=True")]
        public string PharmacyConnectionString {
            get {
                return ((string)(this["PharmacyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\HP\\SOURCE\\REPOS\\LABA2" +
            "5_PHARMACY\\LABA25_PHARMACY\\BIN\\DEBUG\\PHARMACY.MDF;Integrated Security=True;Conne" +
            "ct Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_HP_SOURCE_REPOS_LABA25_PHARMACY_LABA25_PHARMACY_BIN_DEBUG_PHARMACY_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_HP_SOURCE_REPOS_LABA25_PHARMACY_LABA25_PHARMACY_BIN_DEBUG_PHARMACY_MDFCo" +
                    "nnectionString"]));
            }
        }
    }
}
